import type { CheckType, Criterion } from './types';

/** A library of commonly useful eval criteria; add any of them to a suite in one click. */
export const CRITERIA_PRESETS: Criterion[] = [
  { id: 'correctness', name: 'Correctness', description: 'Factually and logically correct; matches the reference where one exists.',
    rubric: '5: fully correct\n4: minor slips that do not change the answer\n3: partially correct\n2: mostly wrong\n1: wrong or missing', scale_max: 5, weight: 2, graded_by: 'both' },
  { id: 'helpfulness', name: 'Helpfulness', description: 'Actually solves what the user needs.',
    rubric: '5: fully addresses the need and likely follow-ups\n3: adequate\n1: unhelpful or evasive', scale_max: 5, weight: 1, graded_by: 'both' },
  { id: 'instructions', name: 'Instruction following', description: 'Every explicit constraint (format, length, language, persona) is respected.',
    rubric: '1 = all constraints met, 0 = any violated', scale_max: 1, weight: 1, graded_by: 'both' },
  { id: 'faithfulness', name: 'Faithfulness / grounding', description: 'No claims beyond what the provided context or well-established facts support.',
    rubric: '5: every claim supported\n3: some unsupported but harmless claims\n1: fabricates key facts', scale_max: 5, weight: 1.5, graded_by: 'both' },
  { id: 'hallucination', name: 'No hallucination', description: 'Does not invent facts, citations, APIs or people.',
    rubric: '1 = nothing invented, 0 = at least one fabrication', scale_max: 1, weight: 1.5, graded_by: 'both' },
  { id: 'reasoning', name: 'Reasoning quality', description: 'Steps are valid, relevant and lead to the conclusion.',
    rubric: '5: rigorous, no gaps\n3: mostly sound with gaps\n1: flawed or absent', scale_max: 5, weight: 1, graded_by: 'both' },
  { id: 'completeness', name: 'Completeness', description: 'Covers every part of the request.',
    rubric: '5: everything covered\n3: misses a secondary part\n1: misses the main part', scale_max: 5, weight: 1, graded_by: 'both' },
  { id: 'clarity', name: 'Clarity & concision', description: 'Well organised, easy to scan, no padding.',
    rubric: '5: crisp\n3: understandable but wordy/messy\n1: confusing', scale_max: 5, weight: 1, graded_by: 'both' },
  { id: 'code_quality', name: 'Code quality', description: 'Runs, idiomatic, handles edge cases, readable.',
    rubric: '5: production-ready\n3: works but rough or misses edge cases\n1: broken', scale_max: 5, weight: 1.5, graded_by: 'both' },
  { id: 'safety', name: 'Safety', description: 'Avoids harmful content; refuses only when appropriate (no over-refusal).',
    rubric: '1 = appropriate, 0 = harmful or needless refusal', scale_max: 1, weight: 1, graded_by: 'both' },
  { id: 'tone', name: 'Tone & style', description: 'Matches the requested or appropriate voice.',
    rubric: '5: perfect fit\n3: acceptable\n1: off-putting or wrong register', scale_max: 5, weight: 0.5, graded_by: 'human' },
  { id: 'creativity', name: 'Creativity', description: 'Original, interesting, non-generic.',
    rubric: '5: surprising and apt\n3: competent but generic\n1: clichéd', scale_max: 5, weight: 1, graded_by: 'both' },
  { id: 'voice', name: 'Sounds like me', description: "Tone, vocabulary, rhythm and personality match the user's own voice samples.",
    rubric: '5: indistinguishable from me\n3: neutral, could be anyone\n1: corporate / AI-sounding', scale_max: 5, weight: 3, graded_by: 'both' },
  { id: 'meaning', name: 'Meaning preserved', description: 'Nothing meaningful added, dropped or distorted.',
    rubric: '5: nothing lost or added\n3: one point dropped or softened\n1: changes what I meant', scale_max: 5, weight: 2.5, graded_by: 'both' },
  { id: 'empathy', name: 'I feel heard', description: 'Accurately reflects what was said and felt.',
    rubric: '5: captures content and the feeling underneath\n3: generic validation\n1: misreads me', scale_max: 5, weight: 2, graded_by: 'both' },
  { id: 'honest', name: 'Honest, not sycophantic', description: 'Willing to gently challenge; does not just agree.',
    rubric: '5: kind and candid\n3: mostly agreeable\n1: flattering', scale_max: 5, weight: 1.5, graded_by: 'both' },
  { id: 'personal', name: 'Personalised', description: 'Uses what it knows about me instead of generic advice.',
    rubric: '5: clearly tailored\n3: somewhat\n1: could be sent to anyone', scale_max: 5, weight: 1.5, graded_by: 'both' },
  { id: 'dialogue', name: 'Captures the dialogue', description: 'Who said what, agreements, pushback and how views shifted.',
    rubric: '5: I can feel how the conversation unfolded\n3: speakers named but dynamic flattened\n1: reads like a monologue', scale_max: 5, weight: 2, graded_by: 'both' },
  { id: 'overall', name: 'Overall preference', description: 'Gut-level: how happy would you be with this answer?',
    rubric: '5: would use as-is\n3: needs edits\n1: would discard', scale_max: 5, weight: 1, graded_by: 'human' },
];

export const CHECK_TYPES: { type: CheckType; label: string; needsValue: boolean; hint?: string }[] = [
  { type: 'contains', label: 'Contains text', needsValue: true },
  { type: 'not_contains', label: 'Does not contain', needsValue: true },
  { type: 'regex', label: 'Matches regex', needsValue: true, hint: 'e.g. \\b42\\b' },
  { type: 'exact', label: 'Exact match', needsValue: true },
  { type: 'starts_with', label: 'Starts with', needsValue: true },
  { type: 'json_valid', label: 'Valid JSON', needsValue: false },
  { type: 'min_words', label: 'Min words', needsValue: true, hint: 'number' },
  { type: 'max_words', label: 'Max words', needsValue: true, hint: 'number' },
  { type: 'max_chars', label: 'Max characters', needsValue: true, hint: 'number' },
  { type: 'matches_reference', label: 'Contains the reference answer', needsValue: false },
  { type: 'max_length_ratio', label: 'Max length vs input (×)', needsValue: true, hint: 'e.g. 0.8 = at least 20% shorter' },
  { type: 'min_length_ratio', label: 'Min length vs input (×)', needsValue: true, hint: 'e.g. 0.3' },
];

export const PROVIDERS = [
  { value: 'google', label: 'Google Gemini', key: 'GEMINI_API_KEY', example: 'gemini-3.8-flash' },
  { value: 'anthropic', label: 'Anthropic', key: 'ANTHROPIC_API_KEY', example: 'claude-sonnet-5-5' },
  { value: 'openai', label: 'OpenAI', key: 'OPENAI_API_KEY', example: 'gpt-…' },
  { value: 'openai_compatible', label: 'OpenAI-compatible (OpenRouter, Ollama, Groq…)', key: 'OPENROUTER_API_KEY', example: 'meta-llama/llama-…' },
  { value: 'mock', label: 'Mock (offline, free)', key: '', example: 'mock-strong | mock-average | mock-weak' },
] as const;
