services:
  db:
    image: postgres:15
    container_name: transcriber-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: transcriber
      POSTGRES_PASSWORD: transcriber
      POSTGRES_DB: transcriber
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: transcriber-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console
    volumes:
      - minio-data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transcriber-backend
    depends_on:
      - db
      - minio
    environment:
      DATABASE_URL: postgresql://transcriber:transcriber@db:5432/transcriber
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: transcriber
      ENVIRONMENT: development
      # Add other environment variables as needed
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  pgdata:
  minio-data: 